# Generated by Django 3.0.7 on 2020-06-18 05:38

import calcularConf.static.rotinas.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import month.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDaEmpresa', models.CharField(max_length=128)),
                ('qtdDeNotasEmitidas', models.PositiveIntegerField()),
                ('qtdDePendencias', models.PositiveIntegerField()),
                ('indiceDeConf', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DadosDasEmpresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json']), calcularConf.static.rotinas.validators.file_size], verbose_name='Arquivo de registros, favor entrar com formato .json')),
                ('month', month.models.MonthField(verbose_name='Selecione o ano e o mês do registro')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcularConf.Empresa')),
            ],
        ),
    ]
