# Generated by Django 2.2.2 on 2020-06-17 20:49

import calcularConf.static.rotinas.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDaEmpresa', models.CharField(max_length=128)),
                ('qtdDeNotasEmitidas', models.PositiveIntegerField()),
                ('qtdDePendencias', models.PositiveIntegerField()),
                ('indiceDeConf', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InfoDasEmpresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json']), calcularConf.static.rotinas.validators.file_size])),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcularConf.Empresa')),
            ],
        ),
    ]
