# Generated by Django 2.2.2 on 2020-06-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDaEmpresa', models.CharField(max_length=128, unique=True)),
                ('qtdDeNotasEmitidas', models.PositiveIntegerField()),
                ('qtdDePendencias', models.PositiveIntegerField()),
                ('indiceDeConf', models.FloatField()),
                ('idDaEmpresa', models.PositiveIntegerField(unique=True)),
            ],
        ),
    ]
