# Generated by Django 2.2.2 on 2020-06-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcularConf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='idDaEmpresa',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
