# Generated by Django 2.2.2 on 2020-06-17 18:14

import calcularConf.static.rotinas.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcularConf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infodasempresas',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json']), calcularConf.static.rotinas.validators.file_size]),
        ),
    ]
