# Generated by Django 2.2.2 on 2020-06-17 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calcularConf', '0002_auto_20200617_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='infodasempresas',
            name='id',
            field=models.AutoField(auto_created=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infodasempresas',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcularConf.Empresa'),
        ),
    ]
