# Generated by Django 3.0.7 on 2020-06-17 21:21

from django.db import migrations
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('calcularConf', '0003_auto_20200617_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='infodasempresas',
            name='month',
            field=month.models.MonthField(help_text='Entre com um mês', unique=True, verbose_name='Mês e ano',null=False,blank=False),
            preserve_default=False,
        ),
    ]
