# Generated by Django 3.0.7 on 2020-06-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcularConf', '0003_auto_20200615_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nomeDaEmpresa',
            field=models.CharField(max_length=128),
        ),
    ]
