# Generated by Django 2.2.2 on 2020-06-17 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calcularConf', '0003_auto_20200617_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infodasempresas',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='calcularConf.Empresa'),
        ),
    ]
