# Generated by Django 2.2.2 on 2020-06-17 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calcularConf', '0004_auto_20200617_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infodasempresas',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='calcularConf.Empresa'),
        ),
    ]
