# Generated by Django 3.0.7 on 2020-06-17 21:58

import calcularConf.static.rotinas.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('calcularConf', '0004_infodasempresas_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosDasEmpresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json']), calcularConf.static.rotinas.validators.file_size])),
                ('month', month.models.MonthField(unique=True, verbose_name='Por favor entre com mês e ano do registro')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcularConf.Empresa')),
            ],
        ),
        migrations.DeleteModel(
            name='InfoDasEmpresas',
        ),
    ]
