# Generated by Django 3.0.7 on 2020-06-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcularConf', '0004_auto_20200615_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='indiceDeConfInt',
            new_name='indiceDeConf',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='indiceDeConfFloat',
        ),
    ]
