# Generated by Django 3.0.7 on 2020-06-16 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcularConf', '0005_auto_20200616_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='idDaEmpresa',
        ),
    ]
