# Generated by Django 3.0.7 on 2020-06-17 22:03

from django.db import migrations
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('calcularConf', '0005_auto_20200617_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosdasempresas',
            name='month',
            field=month.models.MonthField(verbose_name='Ano e mês'),
        ),
    ]
