# Generated by Django 3.0.7 on 2020-06-18 03:47

import calcularConf.static.rotinas.validators
import django.core.validators
from django.db import migrations, models
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('calcularConf', '0006_auto_20200617_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosdasempresas',
            name='arquivo',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json']), calcularConf.static.rotinas.validators.file_size], verbose_name='Arquivo de registros, favor entrar com formato .json'),
        ),
        migrations.AlterField(
            model_name='dadosdasempresas',
            name='month',
            field=month.models.MonthField(verbose_name='Selecione o ano e o mês do registro'),
        ),
    ]
